name: 'Lean release tagging'
description: 'Creates a Git tag whenever your project updates to a new Lean release.'
inputs:
  GITHUB_TOKEN:
    description: 'Token used to access the GitHub API. When in doubt, set this to the value of secrets.GITHUB_TOKEN.'
    required: true
  before:
    description: 'Commit hash of the most recent commit before the push. Unless you know what you are doing, you do not need to change this.'
    required: false
    default: ${{ github.event.before }}
  after:
    description: 'Commit hash of the most recent commit after the push. Unless you know what you are doing, you do not need to change this.'
    required: false
    default: ${{ github.event.after }}
  do-release:
    description: 'Whether to create a GitHub release for the new tag. Allowed values: `true` and `false`. Default value: `false`.'
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - name: Checkout the repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        # We set infinite fetch depth, for now, because we can't tell how many revisions are between
        # `before` and `after` before actually accessing the repo.
        fetch-depth: 0

    - name: Run the script
      run: ${{ github.action_path }}/create-tags.sh
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        BEFORE: ${{ inputs.before }}
        AFTER: ${{ inputs.after }}
        DO_RELEASE: ${{ inputs.do-release }}
