
on:
  push:
    branches:
      - 'testing'
    paths:
      - 'lean-toolchain'

jobs:
  lean-release-tag:
    name: Add Lean release tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: lean-release-tag action
      uses: leanprover-community/lean-release-tag@001bf971d3f9c445468237ee487f26ea9e85bf35
      with:
        before: ${{ github.event.before }}
        after: ${{ github.event.after }}

