
on:
  push:
    branches:
      - 'testing'
    paths:
      - 'lean-toolchain'

jobs:
  lean-release-tag:
    name: Add Lean release tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: lean-release-tag action
      uses: leanprover-community/lean-release-tag@f21a6eedf2ee1299214bd045fde3ad9a7f61e606
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        before: ${{ github.event.before }}
        after: ${{ github.event.after }}

        do-release: true
