
on:
  push:
    branches:
      - 'testing'
    paths:
      - 'lean-toolchain'

jobs:
  lean-release-tag:
    name: Add Lean release tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: lean-release-tag action
      uses: leanprover-community/lean-release-tag@cd9ace2119a521d567bf0659eb6c5cb449461981
      with:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        before: ${{ github.event.before }}
        after: ${{ github.event.after }}

