
on:
  push:
    branches:
      - 'testing'
    paths:
      - 'lean-toolchain'

jobs:
  lean-release-tag:
    name: Add Lean release tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: lean-release-tag action
      uses: leanprover-community/lean-release-tag@6cac285cc62ca3c14a396be0945cdf06e3ac8593
      with:
        before: ${{ github.event.before }}
        after: ${{ github.event.after }}

