
on:
  push:
    branches:
      - 'testing'
    paths:
      - 'lean-toolchain'

jobs:
  lean-release-tag:
    name: Add Lean release tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: lean-release-tag action
      uses: leanprover-community/lean-release-tag@403d831019019ed3518f987b2bdb5361fb7ad9ce
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

