
on:
  push:
    branches:
      - 'testing'
    paths:
      - 'lean-toolchain'

jobs:
  lean-release-tag:
    name: Add Lean release tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: lean-release-tag action
      uses: leanprover-community/lean-release-tag@65ed38eff64b90fa1d1d1c0d475f1f64ba8f7708
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        do-release: true
